# Generated by Django 4.2.7 on 2023-12-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mixing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixing',
            name='mix',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow')], default='R', max_length=1),
        ),
    ]
