# Generated by Django 4.2.7 on 2023-12-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_mixing_options_alter_mixing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='votes',
            field=models.ManyToManyField(to='main_app.vote'),
        ),
    ]
