# Generated by Django 4.2.7 on 2023-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vote_color_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('stars', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='color',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='color',
            name='stars',
            field=models.ManyToManyField(to='main_app.star'),
        ),
    ]
