# Generated by Django 4.2.7 on 2023-12-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_star_remove_color_votes_delete_vote_color_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='star',
            name='stars',
            field=models.CharField(max_length=1),
        ),
    ]
