# Generated by Django 4.2.7 on 2023-12-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_star_name_alter_star_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='name',
        ),
        migrations.AddField(
            model_name='star',
            name='review',
            field=models.TextField(default='No review yet'),
        ),
    ]
