# Generated by Django 4.2.7 on 2023-12-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_star_name_star_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixing',
            options={},
        ),
        migrations.RemoveField(
            model_name='mixing',
            name='date',
        ),
    ]
